# Generated by Django 5.2 on 2026-02-27 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip',
            name='ciutat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='edat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='posicio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lliga',
            name='temporada',
            field=models.CharField(default='temporada', max_length=50),
        ),
        migrations.AlterField(
            model_name='equip',
            name='lliga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equips', to='futbol.lliga'),
        ),
        migrations.AlterField(
            model_name='event',
            name='jugador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_fets', to='futbol.jugador'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='equip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadors', to='futbol.equip'),
        ),
        migrations.AlterField(
            model_name='partit',
            name='lliga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partits', to='futbol.lliga'),
        ),
    ]
